### ISSUE TITLE
pipe wallabag output

### ISSUE THREAD

**Issue by ghost** [Nepochal/wallabag-cli#6] opened 2020-01-28 12:21 UTC
Don't why i can't pipe the wallabag-cli output ?!

`wallabag list > entries-list.txt`

`Traceback (most recent call last):

  File "wallabag/wallabag.py", line 315, in <module>

  File "wallabag/wallabag_list.py", line 43, in list_entries

  File "wallabag/entry.py", line 37, in entrylist

  File "wallabag/entry.py", line 21, in __init__

AttributeError: 'NoneType' object has no attribute 'replace'

[6639] Failed to execute script wallabag`

After a long time :

`real	0m24,728s

user	       0m3,133s

sys	      0m0,708s
`

**Comment by The-Compiler** [comment] 2020-01-28 12:49
Works fine for me FWIW. Are you sure you don't get the same error if you run `wallabag list` normally?

**Comment by mehkera** [comment] 2020-01-28 13:07
I'am on ubuntu 18.04 , wallabag list work great , i have alist of the lastest entiries !

**Comment by The-Compiler** [comment] 2020-01-28 15:10
That's weird. It's crashing here:

https://github.com/Nepochal/wallabag-cli/blob/9e5d97ee8c20566f2c04eca3c324cb1ed6f52ea0/wallabag/entry.py#L21

which means there's an entry without a title somewhere. I have no idea why that'd be the case only with the output redirection.

**Comment by Nepochal** [comment] 2020-12-17 07:25
Sorry, I also was not able to reproduce your error.
Redirecting and piping the output of 'wallabag list' and 'wallabag show' works great on Arch Linux, Debian 10 and Debian over WSL on my machines.

I will close this issue.

**Closed by Nepochal** 2020-12-17 07:25 UTC
